### ISSUE TITLE
Widen FC mount holes

### ISSUE THREAD

**Issue by datamafia** [rotorgarage/fairlane#1]
Currently the FC is 30mm (KISS) and we need 30.5mm to support majority stack PCBs.

**Comment by Mr-A-Designs** [comment]
Widen the rear standoff spacing for access to USB ports that are in the stack. Both base and top plate hole spacing. (Diatone SP3 VTX) Current 10.75 mm from center line.

**Comment by datamafia** [comment]
FC fixed in 328292c07de3c460b28aa764275290e718292aa9. Moving second comment to separate issue.
